language: elixir
sudo: required

elixir:
  - 1.9
  - 1.10
  - 1.11
otp_release:
  - 23.0

before_script:
  - make pull_deps
  - make linter
script:
  - make unit_test
after_script:
  - make docs_report
after_success:
  - bash <(curl -s https://codecov.io/bash)
